services:
  - type: web
    name: aternos-auto-booster
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python scripts/setup_env.py
    startCommand: python run.py
    envVars:
      - key: ATERNOS_USERNAME
        value: "_CRAFTEEE_"
      - key: ATERNOS_PASSWORD
        value: "Albin4242"
      - key: ATERNOS_SERVER
        value: "gameplannet.aternos.me"
      - key: BOOST_INTERVAL
        value: "60"
      - key: MAX_ATTEMPTS_PER_SESSION
        value: "240"
    healthCheckPath: /health
