services:
  - type: web
    name: aternos-24-7-keeper
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser chromium-chromedriver
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ATERNOS_USERNAME
        value: "_CRAFTEEE_"
      - key: ATERNOS_PASSWORD
        value: "Albin4242"
      - key: ATERNOS_SERVER
        value: "gameplannet.aternos.me:43658"
      - key: AUTO_START
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
